# Generated by Django 5.1.1 on 2024-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='registration method'),
        ),
    ]
