# Generated by Django 5.1.1 on 2024-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='disk_size',
            field=models.IntegerField(default=1, help_text='Disk size in GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='memory_size',
            field=models.IntegerField(default=1, help_text='Memory size in KIB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='vcpu_count',
            field=models.IntegerField(default=1),
        ),
    ]
