apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: hynfratech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hynfratech
  template:
    metadata:
      labels:
        app: hynfratech
    spec:
      containers:
      - name: django-container
        image: antonymwangig/hynfratech:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
            name: django-secret

# Allowing External Access using a Service
---
apiVersion: v1
kind: Service
metadata:
  name: hynfratech
  labels:
    app: hynfratech
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: hynfratech