apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: hynfratech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hynfratech
  template:
    metadata:
      labels:
        app: hynfratech
    spec:
      containers:
      - name: django-container
        image: antonymwangig/hynfratech:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
# Allowing External Access using a Service
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: hynfratech
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: hynfratech