apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.2-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "hyn"
        - name: POSTGRES_USER
          value: "hyn_user"
        - name: POSTGRES_PASSWORD
          value: "hyn_passcode"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pv-claim
