# Generated by Django 5.1.1 on 2024-09-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_remove_virtualmachine_project_virtualmachine_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'permissions': [('can_change_owner', 'Move VMs between users')]},
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='disk_image_path',
            field=models.CharField(default=None, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='vm_name',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='memory_size',
            field=models.IntegerField(help_text='Memory size in KIB'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
