# Generated by Django 5.1.1 on 2024-09-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_virtualmachine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='state',
            field=models.CharField(choices=[('Running', 'Running'), ('Blocked', 'Blocked'), ('Paused', 'Paused'), ('Shutdown', 'Shutdown'), ('Shutoff', 'Shutoff'), ('Crashed', 'Crashed'), ('No state', 'No state'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
    ]
