name: Dev CICD
on:
  push:
    branches: [ main ]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build_test:
    name: Build Test
    uses: ./.github/workflows/build_test.yml

  deploy:
    name: Deploy
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          DEV_SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          DEV_SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          DEV_SSH_USER: ${{ secrets.DEV_SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEV_SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $DEV_SSH_HOST
            User $DEV_SSH_USER
            Port $DEV_SSH_PORT
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: Run deploy
        run: |
          ssh target "docker-compose down && git pull && docker-compose build && docker-compose up -d --force-recreate"