name: PROD DEPLOY
on: [workflow_call]
concurrency:
  group: main
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          PROD_SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
          PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PROD_SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $PROD_SSH_HOST
            User $PROD_SSH_USER
            Port $PROD_SSH_PORT
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Deploy to Kubernetes
        run: |
          ssh target << 'EOF'
          set -e

          echo "Pulling the latest code..."
          cd hynfratechbe/
          git pull || { echo 'git pull failed'; exit 1; }

          echo "Applying Kubernetes manifests... pvc-postgres "
          kubectl apply -f k8s/pvc-postgres.yaml || { echo 'kubectl pvc-postgres apply failed'; exit 1; }

          echo "Applying Kubernetes manifests... postgres"
          kubectl apply -f k8s/postgres.yaml || { echo 'kubectl postgres apply failed'; exit 1; }

          echo "Applying Kubernetes manifests..."
          kubectl apply -f k8s/postgres-service.yaml || { echo 'kubectl posgres service apply failed'; exit 1; }
          
          echo "Applying Kubernetes manifests... hyn app"
          kubectl apply -f k8s/hyn-app.yaml || { echo 'kubectl apply failed'; exit 1; }

          echo "Applying Kubernetes manifests.. hyn app service."
          kubectl apply -f k8s/hyn-app-service.yaml || { echo 'kubectl apply failed hyn app service'; exit 1; }

          echo "Checking rollout status..."
          kubectl rollout status deployment/hyn-deployment || { echo 'Deployment rollout failed'; exit 1; }

          echo "Kubernetes deployment successful!"
          EOF