name: PROD DEPLOY
# on: [workflow_call]
on:
  push:
    branches: [ main ]
concurrency:
  group: main
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        env:
          PROD_SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
          PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PROD_SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $PROD_SSH_HOST
            User $PROD_SSH_USER
            Port $PROD_SSH_PORT
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      -
        name: Test SSH connection
        run: |
          ssh target "echo 'SSH connection successful!' || { echo 'SSH connection failed'; exit 1; }"

      - name: Deploy to Kubernetes
        run: |
          ssh target << 'EOF'
          set -e

          echo "Pulling the latest code..."
          cd hynfratechbe/
          git pull || { echo 'git pull failed'; exit 1; }

          echo "Applying Kubernetes manifests... pvc-postgres  config"
          kubectl apply -f k8s/ps-config.yaml || { echo 'kubectl pvc-postgres apply failed'; exit 1; }

          echo "Applying Kubernetes manifests... postgres pv"
          kubectl apply -f k8s/psql-pv.yaml || { echo 'kubectl postgres apply failed'; exit 1; }

          echo "Applying Kubernetes manifests.. claim."
          kubectl apply -f k8s/psql-claim.yaml || { echo 'kubectl posgres service apply failed'; exit 1; }
          
          echo "Applying Kubernetes manifests.. postgs deploy."
          kubectl apply -f k8s/postgres.yaml || { echo 'kubectl posgres service apply failed'; exit 1; }
          
          echo "Applying Kubernetes manifests.. service."
          kubectl apply -f k8s/ps-service.yaml || { echo 'kubectl posgres service apply failed'; exit 1; }
          
          echo "Applying Kubernetes manifests... hyn app"
          kubectl apply -f k8s/django-deployment.yaml || { echo 'kubectl apply failed'; exit 1; }
          
          echo "Checking rollout status..."
          kubectl rollout status deployment/hynfratech || { echo 'Deployment rollout failed'; exit 1; }

          echo "Kubernetes deployment successful!"
          EOF